const industryOptions = [
	"All Sector (specilisation in Deep Tech)",
	"Agnostic",
	"Tech Enabled",
	"Agriculture",
	"AgriTech / AgTech",
	"Food Tech",
	"Clean Energy",
	"AI",
	"Robotics",
	"E-commerce",
	"Property",
	"Energy",
	"Health",
	"Transportation",
	"FinTech",
	"Quantum Computing",
	"Crypto",
	"Medtech",
	"Automation",
	"Hardware and Engineering",
	"Sustainability",
	"B2B commercial technologies",
	"cybersecurity",
	"defence",
	"supply chain",
	"public wellness",
	"Saas",
	"Consumer",
	"Logistics",
	"Marketplace",
	"Media, Advertising, Marketing",
	"Biotechnology",
	"Life Sciences",
	"DLT / Blockchain",
	"Environment",
	"Clean Energy",
	"Sustainable Food",
	"Carbon",
	"Clean Tech",
	"Climate Tech",
	"Ocean health",
	"waste & recycling",
	"Construction",
	"Manufacturing",
	"Space",
	"Data Centric Companies",
	"Advance Manufacturing",
	"Digitlisation",
	"Biotech",
	"Medical Devices",
	"Diagnostics",
	"Impact",
	"InsurTech",
	"IOT",
	"BioTech",
	"Life Sciences",
	"PropTech",
	"Secondaires",
	"Web3",
	"Edtech",
  ];
  
  export default industryOptions;
  